'''
Created on Dec 3, 2019

@author: ctate
'''
from asyncio.tasks import wait
from test.test_logging import secs
from time import sleep
if __name__ == '__main__':
    print("abcdefghijklmnopqrstuvwxyz")
    print("that is how you spell the alphabet")
    print("a")
    sleep(1)
    print("b")
    sleep(1)
    print("c")
    sleep(1)
    print("d")
    sleep(1)
    print("e")
    sleep(1)
    print("f")
    sleep(1)
    print("g")
    sleep(1)
    print("h")
    sleep(1)
    print("i")
    sleep(1)
    print("j")
    sleep(1)
    print("k")
    sleep(1)
    print("l")
    sleep(1)
    print("m")
    sleep(1)
    print("n")
    sleep(1)
    print("o")
    sleep(1)
    print("p")
    sleep(1)
    print("q")
    sleep(1)
    print("r")
    sleep(1)
    print("s")
    sleep(1)
    print("t")
    sleep(1)
    print("u")
    sleep(1)
    print("v")
    sleep(1)
    print("w")
    sleep(1)
    print("x")
    sleep(1)
    print("y")
    sleep(1)
    print("z")
    sleep(1)